### ISSUE TITLE
Add linter

### ISSUE THREAD

**Issue by jofftiquez** [OSSPhilippines/freefolio#25] opened 2022-10-05 00:11 UTC
Add eslint. Rules:

- 2 spaces for tabs
- single quote over double quotes
- space before parens in methods

**Comment by tahseenzahra** [comment] 2022-10-07 09:13
@jofftiquez those changes weren't merged into your main so I can take that to my local system and add further changes
I forked your repo and made the changes there that according to my understanding are required for this.

**Comment by tahseenzahra** [comment] 2022-10-07 09:30
@jofftiquez it would be great if you merge the files of @rgvillanueva28 and then I can pull it and make any further changes that are required 
and if you don't wanna merge the changes I made can you please add the hacktoberfest accepted of any of the tags that are required for the acceptance of the pr in hacktoberfest

**Comment by rgvillanueva28** [comment] 2022-10-08 05:55
Since the issue is for rules only, I only made the minimum requirements.
I agree with @tahseenzahra. I suggest that after merging, maybe we could do issues for linting of the themes. @jofftiquez

**Comment by jofftiquez** [comment] 2022-10-10 00:47
Hello thanks @tahseenzahra and @rgvillanueva28 merging this now

**Comment by David-Ramboy** [comment] 2022-10-31 23:05
Is this issue already resolve?

**Closed** 2023-03-30 08:10 UTC
